version: 2
jobs:

  deploy_master:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm run install
      - run:
          name: Add .env
          command: |
            echo "WEBSITE_URL=$WEBSITE_URL"> src/.env
            echo "API_URL=API_URL">> src/.env
            echo "FIREBASE_API_KEY=$FIREBASE_API_KEY" >> src/.env
            echo "FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN" >> src/.env
            echo "FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL" >> src/.env
            echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> src/.env
            echo "FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET" >> src/.env
            echo "FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID" >> src/.env
            echo "FIREBASE_APP_ID=$FIREBASE_APP_ID" >> src/.env
            echo "FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID" >> src/.env
            echo "FIREBASE_MESSAGING_VAP_ID=FIREBASE_MESSAGING_VAP_ID" >> src/.env
      - run:
          name: Add firebase-messaging-sw.js
          command: |
            echo "importScripts('https://www.gstatic.com/firebasejs/7.15.0/firebase-app.js')" > src/static/firebase-messaging-sw.js
            echo "importScripts('https://www.gstatic.com/firebasejs/7.15.0/firebase-messaging.js')" >> src/static/firebase-messaging-sw.js
            echo "" >> src/static/firebase-messaging-sw.js
            echo "firebase.initializeApp({" >> src/static/firebase-messaging-sw.js
            echo "  apiKey: '$FIREBASE_API_KEY'," >> src/static/firebase-messaging-sw.js
            echo "  projectId: '$FIREBASE_PROJECT_ID'," >> src/static/firebase-messaging-sw.js
            echo "  messagingSenderId: '$FIREBASE_MESSAGING_SENDER_ID'," >> src/static/firebase-messaging-sw.js
            echo "  appId: '$FIREBASE_APP_ID'" >> src/static/firebase-messaging-sw.js
            echo "})" >> src/static/firebase-messaging-sw.js
            echo "" >> src/static/firebase-messaging-sw.js
            echo "const messaging = firebase.messaging()" >> src/static/firebase-messaging-sw.js
            echo "" >> src/static/firebase-messaging-sw.js
            echo "messaging.setBackgroundMessageHandler((payload) => {" >> src/static/firebase-messaging-sw.js
            echo "  console.log('firebase-messaging-sw.js setBackgroundMessageHandler', payload)" >> src/static/firebase-messaging-sw.js
            echo "})" >> src/static/firebase-messaging-sw.js
            echo "" >> src/static/firebase-messaging-sw.js
      - run:
          name: deploy to Firebase Hosting
          command: ./src/node_modules/.bin/firebase deploy --project=$FIREBASE_PROJECT_ID --token=$FIREBASE_CI_TOKEN
      - run:
          name: Call to warm up
          command: |
            curl "$WEBSITE_URL"
            curl "$WEBSITE_URL/api/healthy"
            curl "$WEBSITE_URL/sitemap.xml"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy_master:
          filters:
            branches:
              only: master
